/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/drone_final.glb --typescript 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/drone_final.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Electronics_Case.geometry} material={nodes.Electronics_Case.material} position={[0, -0.029, 0]} scale={[0.619, 0.441, 0.736]} />
      <mesh geometry={nodes.Plates_Top.geometry} material={nodes.Plates_Top.material} position={[0, 0.022, 0]} scale={0.591} />
      <mesh geometry={nodes.Plates_Bottom.geometry} material={nodes.Plates_Bottom.material} position={[0, -0.394, 0]} />
      <mesh geometry={nodes.Stands_High_Octo.geometry} material={nodes.Stands_High_Octo.material} position={[0, -0.785, 0]} rotation={[Math.PI / 2, 0, 0]} scale={1.003} />
    </group>
  )
}

useGLTF.preload('/drone_final.glb')
